# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-22 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('react_cms', '0002_contentresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFiled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('file', models.FileField(upload_to='cms/files')),
            ],
        ),
        migrations.AlterField(
            model_name='contentresource',
            name='json',
            field=models.TextField(blank=True, null=True, verbose_name='Components'),
        ),
    ]
