# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-22 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('react_cms', '0003_auto_20170122_1616'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadedFiled',
            new_name='UploadedFile',
        ),
    ]
