# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-22 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('react_cms', '0004_auto_20170122_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentresource',
            name='rendered',
            field=models.TextField(blank=True, null=True, verbose_name='Rendered component'),
        ),
    ]
